---
- name: Add master to hosts
  lineinfile:
    path: /etc/hosts
    line: "192.168.0.150 master-1"

- name: Install required packages
  pacman:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
  - virt-manager 
  - qemu 
  - vde2 
  - ebtables 
  - dnsmasq 
  - bridge-utils 
  - openbsd-netcat
  
- name: Remove the virtual network
  command:
    cmd: virsh net-destroy host-bridge
  ignore_errors: yes

- name: Create the virtual network
  command:
    cmd: "virsh net-create {{ playbook_dir }}/files/host-bridge.xml"
  ignore_errors: yes