---
tasks:
  - name: Destroy workers
    with_sequence: count={{ worker_count }}
    become: yes
    hosts: local
    roles:
      - destroy_vms
    vars:
      vm_name: "worker-{{ '%d'|format(item|int) }}"
      vm_index: "{{ '%d'|format(item|int) }}"
  - name: Destroy master
    become: yes
    hosts: local
    roles:
      - destroy_vms
    vars:
      vm_name: "master-1"
      vm_index: "0"